import { DocContent } from "@/types/docs";

export const releasePipelines: DocContent = {
  title: "Release Pipelines (CD)",
  description:
    "Understand the Continuous Deployment architecture used to safely push Managed Solutions through QA, UAT, and Production environments.",
  content: `
## Introduction

The **Release Pipeline** represents the "Continuous Deployment (CD)" half of CI/CD.

Its sole responsibility is to grab the Build Artifact (the Managed Solution \\\`.zip\\\` file) generated by the Build Pipeline, and systematically push it into downstream environments (QA, UAT, Production).

## Environments and Stages

Unlike a Build Pipeline, which is usually a single linear script, a Release Pipeline is broken into distinct **Stages** with strict quality gates.

1. **Stage 1: QA (Quality Assurance)**
   - Automatically triggered as soon as the Build Pipeline finishes.
   - Imports the Managed Solution.
   - Triggers automated UI testing (e.g., Selenium or Playwright) against the newly deployed environment.

2. **Stage 2: UAT (User Acceptance Testing)**
   - Requires a **Pre-deployment Approval**.
   - The pipeline pauses and sends an email to the Business Analyst. The BA must click "Approve" in Azure DevOps before the pipeline will import the solution into the UAT environment.

3. **Stage 3: Production**
   - Requires multiple approvals (e.g., IT Change Advisory Board, Business Owner).
   - Can be scheduled to only deploy during specific maintenance windows (e.g., Saturday at 2:00 AM) to minimize user disruption.

## The Import Process

The actual tasks executed inside a stage are relatively simple:

1. **Tool Installer:** Download the PAC CLI.
2. **Ping Environment:** Ensure the target environment is awake.
3. **Import Solution:** Pushes the Managed ZIP file into the environment. 
   - *Best Practice:* Always check the "Publish Customizations" and "Activate Plugins" boxes to ensure the solution is immediately live after import.
4. **Deploy Configuration Data:** (Optional) If your solution relies on reference data (e.g., standard Tax Rate records that must exist in Prod), use the Configuration Migration tool via the command line to push the data immediately after the solution imports.

## Handling Environment Variables (deploymentSettings.json)

The most complex part of a Release Pipeline is handling Environment Variables and Connection References.

If your solution contains a Power Automate flow that connects to a SharePoint site, the Dev flow points to \\\`https://contoso.sharepoint.com/sites/Dev\\\`, but the Prod flow must point to \\\`https://contoso.sharepoint.com/sites/Prod\\\`.

You cannot deploy the solution without telling Dataverse which SharePoint site to use in Production. If you fail to do this, the flow will break upon import.

To solve this, Azure DevOps allows you to generate a **\\\`deploymentSettings.json\\\`** file. 
Inside this JSON file, you map your Environment Variables and Connection References to dynamic Azure DevOps Variables. 
During the "Import Solution" task, you pass this JSON file. The task will intercept the deployment and dynamically replace the DEV values with the PROD values mid-flight as it injects the solution into the Production database.

## Zero-Downtime Deployments (Real-World Perspective)

Deploying a Managed Solution in Dataverse is generally safe, but it can cause temporary SQL locks on the database tables being updated.

If you are deploying a massive schema update to the Account table while 500 salespeople are actively trying to save accounts, they may encounter fatal SQL timeouts and lose their work.

**Architectural Rule:** For this reason, Production stages in the Release Pipeline are almost always scheduled to execute outside of standard business hours. True "zero-downtime" deployment is extremely difficult in Dataverse due to its monolithic relational nature.

## Things to Remember

- Release Pipelines push the **Managed ZIP** to downstream environments.
- Use **Pre-deployment Approvals** to gate UAT and Production.
- Use a **\\\`deploymentSettings.json\\\`** file to inject environment-specific URLs and credentials.
- Schedule Production deployments during **maintenance windows** to avoid locking errors.

## What's Next

We've covered the mechanical process of pipelines, but we need to discuss the philosophical rules of moving these solutions. We'll summarize the golden rules in **Solution Deployment Strategies**.
  `.trim(),
};
