import { DocContent } from "@/types/docs";

export const automatedFlows: DocContent = {
  title: "Automated Flows",
  description:
    "Learn about Automated Cloud Flows, the backbone of system integration and business process automation in Power Automate.",
  content: `
## Introduction

The vast majority of enterprise integrations and background processes do not require human interaction to start. They react to events happening in the system or in the outside world.

For this, we use an **Automated Cloud Flow**.

## What is an Automated Flow?

An Automated Flow is triggered by an event. It constantly listens in the background, waiting for a specific condition to be met across any of the hundreds of connected services.

## Common Use Cases

- **Data Syncing:** When a new row is added to a SQL Server database, create a corresponding Account in Dataverse.
- **Notifications:** When an Opportunity is marked as "Won" in Dynamics 365, send a celebratory message to a Microsoft Teams channel.
- **Email Processing:** When an email arrives in a shared inbox with an attachment, extract the PDF and save it to SharePoint.

## Popular Automated Triggers

Power Automate has thousands of triggers, but these are the most common in enterprise architectures:

### 1. Dataverse Triggers
The most critical trigger for Dynamics 365 developers. It fires when a record is **Added, Modified, or Deleted**. (We will cover this in deep detail in a dedicated section).

### 2. SharePoint Triggers
Fires when a file is created in a folder, or an item is added to a SharePoint List. Commonly used to ingest legacy data drops from vendors.

### 3. Office 365 Outlook
Fires on incoming emails. It can be heavily filtered (e.g., "Only trigger if the subject contains 'Invoice' and it has an attachment").

### 4. HTTP Webhooks
Fires when an external system (like SAP or Stripe) sends an HTTP POST request to a unique URL generated by Power Automate. This allows real-time integration from systems that don't have native Power Automate connectors.

## Synchronous vs Asynchronous

**Crucial Architecture Note:** Automated Cloud Flows are fundamentally **Asynchronous**.

When an Account is created in Dataverse, and an Automated Flow is triggered, the user who created the Account does *not* wait for the flow to finish. The record saves instantly, and the flow spins up in the background seconds (or sometimes minutes) later.

If you have a business requirement that says *"A user cannot save an Account if the VAT number is invalid,"* you **cannot** use an Automated Flow. You must use a synchronous C# Plugin or a real-time Classic Workflow.

## Best Practices

- **Avoid Infinite Loops:** The most common mistake with Automated Flows is creating a loop. If a flow is triggered when a Contact is updated, and an action *inside* that flow updates the exact same Contact, the flow will trigger itself again, infinitely, until Microsoft throttles your environment. Always use Trigger Conditions to prevent this.
- **Handle Service Outages:** Automated flows rely on APIs. If the SharePoint API is down for 5 minutes, your flow will fail. Always implement Error Handling (Try/Catch blocks) in critical automated flows.

## Things to Remember

- Automated Flows trigger on **background events**, not human clicks.
- They execute **asynchronously**.
- They can listen to Dataverse, Office 365, Azure, or third-party APIs.
- They cannot be used to block a user from saving a record.

## What's Next

Automated flows run when something happens. But what if we want a flow to run every Friday at 5:00 PM, regardless of what is happening in the system? Next, we cover **Scheduled Flows**.
  `.trim(),
};
