import { DocContent } from "@/types/docs";

export const indexes: DocContent = {
  title: "Indexes & Database Tuning",
  description:
    "Understand how Dataverse manages Azure SQL Indexes behind the scenes and how architects can influence them to resolve catastrophic query bottlenecks.",
  content: `
## Introduction

In a traditional on-premise SQL database, if a query is running slowly, a Database Administrator (DBA) runs a SQL Profiler trace, identifies the missing index, and executes a \\\`CREATE INDEX\\\` script against the table.

In Dataverse, you do not have a DBA, and you do not have direct access to SQL Server Management Studio. How are indexes managed in a multi-tenant cloud environment?

## The Automatic Tuning Engine

Microsoft heavily relies on **Azure SQL Database Automatic Tuning** for Dataverse.

Behind the scenes, Microsoft's AI constantly monitors the SQL execution plans generated by the FetchXML and OData queries your users execute. 
If the AI detects that users are frequently querying the Account table by the \\\`AccountNumber\\\` field, and those queries are forcing expensive Full Table Scans, the AI will **automatically create a non-clustered index** on that column during an off-hours maintenance window.

If a column stops being queried for 90 days, the AI will automatically drop the index to recover disk space and optimize Write (INSERT/UPDATE) performance.

## Influencing Indexes Manually

While the AI tuning is highly advanced, it requires historical query data to act. If you have a massive enterprise Go-Live event and you know users will be intensely searching by a specific custom field on day one, you cannot afford to wait for the AI to figure it out.

### 1. Quick Find Views (The Forcing Function)
If you must force Dataverse to index a specific text or numeric column immediately, add that column to the **"Quick Find View"** of the table.

When you add a schema column to the "Find Columns" list in the Quick Find View, Dataverse treats this as a hard architectural requirement and instantly provisions a physical SQL index for that column in the background.

> [!CAUTION]
> **Over-Indexing Penalty**
> There is a strict limit to how many columns you can add to a Quick Find View. If you maliciously add 50 columns to the Quick Find View, you force SQL to maintain 50 indexes. This will cause your database Write performance (Create/Update transactions) to absolutely tank, as SQL must rewrite 50 indexes every time a record is saved.

### 2. Microsoft Support Tickets
If you have a highly complex query involving multiple table joins that is consistently timing out, and a single-column Quick Find index does not resolve it, you must open a **Microsoft Support Ticket**.

You provide Microsoft engineering with the exact FetchXML query that is bottlenecking. Their Tier 3 engineers will analyze the SQL Execution Plan on the backend and manually apply a highly optimized composite index directly to your specific cloud database tenant.

## Indexing Architectural Limits

Dataverse places strict architectural limits on what can physically be indexed in SQL.
- **Multiple Lines of Text:** You cannot index massive text fields (e.g., a "Description" field containing 4,000 characters). SQL B-Tree indexes cannot efficiently handle massive strings.
- **Dataverse Search (Cognitive Search):** If you need to perform "fuzzy" or "wildcard" searches across massive text fields, SQL Indexes will completely fail. You must enable **Dataverse Search** (formerly Relevance Search). This securely pushes the data out of Azure SQL and into a dedicated **Azure Cognitive Search** instance, which uses tokenized inverted indexes designed specifically for heavy text searches.

## Things to Remember

- Dataverse uses **Azure AI Automatic Tuning** to dynamically create and drop indexes.
- You can force an immediate index by appending the column to the **Quick Find View**.
- You can request complex composite indexes via **Microsoft Support**.
- For massive text/wildcard searching, rely strictly on **Dataverse Search**, not SQL indexes.

## What's Next

Now that we understand how queries and indexes perform in the background, we must ensure our synchronous code isn't slowing down the application. Next, we cover **Plugin Optimization**.
  `.trim(),
};
