import { DocContent } from "@/types/docs";

export const capacity: DocContent = {
  title: "Understanding and Managing Dataverse Storage Capacity",
  description:
    "Explore Dataverse's tiered storage model (Database, File, Log), learn how capacity is allocated, and discover essential strategies for monitoring, optimizing, and purchasing storage to ensure your Power Platform environments remain performant and compliant.",
  content: `
## Introduction

In the world of cloud computing, efficient resource management is paramount. For organizations leveraging Microsoft Dataverse—the data platform that powers Dynamics 365, Power Apps, and Power Automate—understanding and managing storage capacity is crucial for maintaining system performance, ensuring compliance, and controlling costs. Unlike traditional on-premise systems where administrators might simply add more physical hard drives, cloud storage operates on a consumption-based model, making optimization a key skill.

Microsoft monitors your organization's Dataverse storage usage at the **Tenant** level. A tenant represents your organization's dedicated instance within Microsoft's cloud services, encompassing all your Power Platform environments. If your tenant exceeds its allotted capacity, it enters a "Deficit" state.

**When your tenant is in a capacity deficit, critical operations are impacted:**
- You cannot create new Power Platform environments.
- You cannot copy or restore existing environments.
- You cannot perform certain database operations, such as creating new solutions or importing large datasets.
- Eventually, Microsoft may restrict users from logging in or saving new records, severely impacting business operations and data integrity.

## The Dataverse Storage Model: Three Tiers

Since 2019, Dataverse has utilized a "New Storage Model" (now the standard model) that logically separates data into three distinct storage types. This tiered approach is designed to optimize performance, cost, and data management based on the nature of the data.

### 1. Database Capacity
This tier is for highly optimized, relational data storage, powered by Azure SQL Database. It's designed for rapid querying, transactional integrity, and complex relationships.
- **What it holds:**
    - Standard and custom table rows (e.g., Accounts, Contacts, Cases, custom entities).
    - Metadata for solutions, configurations, security roles, and business process flows.
    - Choices (formerly Option Sets), Lookups, and other structured data.
- **Cost:** This is typically the most expensive storage tier due to its performance and transactional capabilities.

### 2. File Capacity
This tier leverages Azure Blob Storage, optimized for storing large, unstructured binary data.
- **What it holds:**
    - Email attachments.
    - Note attachments (e.g., PDFs, images, documents).
    - Power Apps Component Framework (PCF) binaries and other static resources.
    - Files stored in Dataverse File or Image columns (unless configured for external storage).
- **Cost:** Significantly lower than Database capacity, making it suitable for bulk unstructured data.

### 3. Log Capacity
This tier is dedicated to audit and diagnostic data, crucial for compliance and troubleshooting.
- **What it holds:**
    - Dataverse Audit History (tracking who changed what field, when, and from what value to what value).
    - Plugin Trace Logs (detailed diagnostic information generated by custom code components like plugins and custom workflow activities, stored in the \`Plugin Trace Log\` table).
- **Cost:** The lowest cost tier, reflecting its purpose for historical and diagnostic data that is less frequently accessed than transactional data.

**Why the Three Tiers?**
This separation allows Microsoft to provide different performance characteristics and cost structures for varying data types. Transactional data (Database) requires high-speed access and integrity, while large files (File) are better suited for cost-effective blob storage, and audit logs (Log) have specific retention and access patterns. This model enables organizations to manage costs more effectively by optimizing where different types of data reside.

## How Dataverse Capacity is Allocated

Your Dataverse tenant automatically receives a base level of capacity. For example, many tenants start with a pooled capacity of 10 GB of Database capacity, 20 GB of File capacity, and 2 GB of Log capacity.

Furthermore, every time you purchase a premium user license for Dynamics 365 applications (e.g., Sales Enterprise, Customer Service Enterprise) or Power Apps per user plans, Microsoft accrues incremental capacity to your tenant's pooled storage. For instance, a Dynamics 365 Sales Enterprise license might add +250 MB of Database capacity and +2 GB of File capacity per user.

All this capacity is pooled at the **tenant level**, meaning it's shared across all environments within your organization.

**Monitoring Your Capacity:**
You can monitor your current capacity usage and allocation via the **Power Platform Admin Center (PPAC)**. Navigate to **Resources > Capacity** to view detailed reports on Database, File, and Log consumption across your environments. This is your primary tool for identifying which environments and data types are consuming the most storage.

**Purchasing Additional Capacity:**
If, after exhausting all optimization strategies, your tenant still requires more storage, you must purchase **Capacity Add-ons**. These add-ons are available for Database, File, or Log capacity independently, typically in 1 GB increments, and are purchased through the Microsoft 365 Admin Center. It's crucial to exhaust optimization strategies before resorting to purchasing add-ons, as costs can escalate quickly.

## Capacity Optimization Strategies

Before incurring significant monthly costs on capacity add-ons, experienced administrators and developers prioritize optimizing existing storage. This involves identifying and managing data that consumes excessive space or is no longer needed, aligning with data retention policies and business needs.

### 1. Manage Dataverse Audit Logs
Audit logs can grow substantially over time, especially in busy environments with extensive auditing enabled.
- **Problem:** Unmanaged audit logs can consume hundreds of gigabytes of Log capacity, impacting performance and increasing storage costs.
- **Best Practice:** Define a clear data retention policy based on your organization's compliance requirements (e.g., retain audit data for 3 years, 7 years). Only audit entities and fields that are truly necessary for compliance or business processes.
- **How to Optimize:**
    1.  **Configure Auditing:** In the Power Platform Admin Center (PPAC), navigate to **Environments > [Your Environment] > Audit History**. Here, you can enable/disable auditing for specific entities and fields. Be selective; only audit what's truly necessary.
    2.  **Delete Old Audit Partitions:** Use the PPAC to delete audit log partitions that are older than your defined retention period. This is a critical step to free up Log capacity.
- **Common Mistake:** Enabling auditing for all entities and fields without a clear purpose, or failing to regularly purge old audit data.

### 2. Efficiently Manage File Attachments
File attachments (notes, emails, custom file columns) are a primary consumer of File capacity.
- **Problem:** Storing large volumes of attachments directly in Dataverse can quickly exhaust File capacity, which, while cheaper than Database capacity, is still more expensive than dedicated file storage solutions.
- **Alternatives & Best Practices:**
    -   **SharePoint Integration:** For new attachments, configure SharePoint integration. This automatically stores new email and note attachments in SharePoint (which is significantly cheaper than Dataverse File storage) while maintaining a link in Dataverse.
        *   **When to use:** This is the recommended, out-of-the-box approach for most organizations to manage new attachments. It's easy to set up and maintain.
        *   **Design Consideration:** Ensure SharePoint permissions align with Dataverse security roles to maintain data access control.
    -   **Custom File Offloading (for existing attachments):** For legacy attachments already residing in Dataverse, consider a custom solution to migrate them to external storage like Azure Blob Storage or SharePoint. This typically involves:
        1.  Identifying large attachments in Dataverse (e.g., from the \`Annotation\` table for notes or \`ActivityMimeAttachment\` for emails).
        2.  Downloading the file content programmatically.
        3.  Uploading it to Azure Blob Storage or SharePoint.
        4.  Updating the Dataverse record (e.g., the Note or Email) with a link to the external file and then deleting the original attachment from Dataverse.
        *   **When to use:** For large-scale migration of historical data, specific compliance requirements, or when SharePoint integration isn't feasible for existing data.
        *   **Performance/Scalability:** This can be a resource-intensive operation and should be planned carefully, often executed during off-peak hours.
        *   **Security:** Ensure secure access to external storage and proper handling of file metadata.

    **Conceptual Diagram: Custom File Offloading Process**
    \`\`\`
    [Dataverse Record (e.g., Note with Attachment)]
           | (Attachment Data)
           V
    [Power Automate Flow / Azure Function / Custom App]
           |
           +--- (Read Attachment from Dataverse)
           |
           +--- (Upload File to Azure Blob Storage / SharePoint)
           |
           +--- (Update Dataverse Record with Link to External File)
           |
           +--- (Delete Original Attachment from Dataverse)
           V
    [Azure Blob Storage / SharePoint]
    \`\`\`

### 3. Optimize Plugin Trace Logs
Plugin trace logs are invaluable for debugging custom code (plugins, custom workflow activities) but can quickly consume Log capacity if not managed.
- **Problem:** Setting plugin tracing to "All" in production environments generates excessive logs, bloating the \`Plugin Trace Log\` table and potentially impacting Dataverse performance.
- **Best Practice:**
    -   In **development and test environments**, set plugin tracing to "All" for detailed debugging.
    -   In **production environments**, set plugin tracing to "Exception Only" to capture only critical errors, minimizing log volume.
- **How to Optimize:**
    1.  Navigate to **Settings > Administration > System Settings > Customization tab**. Set "Enable plug-in trace log" to "Exception."
    2.  Regularly delete old trace logs from the \`Plugin Trace Log\` table using Advanced Find or a recurring Bulk Delete job.
- **Common Mistake:** Forgetting to switch tracing from "All" to "Exception Only" when deploying to production, leading to rapid log growth.

### 4. Purge Asynchronous System Jobs
Dataverse uses asynchronous system jobs for background operations. These jobs, once completed or failed, remain in the database.
- **What they are:** Background processes like workflows, Power Automate flows, bulk delete jobs, data imports, rollup field calculations, and other system-initiated background tasks.
- **Problem:** The \`System Job\` (AsyncOperation) table can grow very large, consuming significant Database capacity.
- **Best Practice:** Implement recurring bulk delete jobs to automatically purge completed or failed system jobs older than a defined period (e.g., 30-60 days). This keeps the table lean and improves overall system performance.
- **How to Optimize:**
    1.  Go to **Settings > Data Management > Bulk Delete Records**.
    2.  Create a new bulk delete job targeting the "System Jobs" entity.
    3.  Set criteria to delete jobs with a "Status Reason" of "Completed" or "Failed" and a "Completed On" date older than your retention period.
    4.  Configure the job to run on a recurring schedule (e.g., monthly).
- **Common Mistake:** Deleting *all* system jobs, including pending or in-progress ones, which can disrupt ongoing processes. Be precise with your filter criteria.

### 5. Data Archiving and Lifecycle Management
For very large datasets that need to be retained for compliance or historical analysis but are not actively used, consider archiving.
- **Problem:** Storing inactive historical data in Dataverse consumes expensive Database capacity and can impact query performance for active data.
- **Solution:** Move old, inactive data to cheaper, external storage solutions.
- **Alternatives:**
    -   **Dataverse Long-Term Retention:** A built-in feature for archiving specific rows from selected tables to a managed data lake, providing cost-effective storage and on-demand retrieval. This is Microsoft's recommended approach for long-term Dataverse data archiving.
    -   **Azure Data Lake Storage:** Export data to Azure Data Lake for cost-effective storage and integration with analytics tools.
    -   **Azure SQL Database:** Migrate historical data to a separate Azure SQL Database for structured archiving, especially if complex querying of archived data is required.
- **Design Considerations:**
    -   **Access Patterns:** How frequently will the archived data be accessed, and what are the retrieval performance requirements?
    -   **Compliance:** Ensure the chosen archiving solution meets regulatory requirements for data retention and security.
    -   **Data Integrity:** Maintain relationships and context if data is split between Dataverse and an archive.
    -   **Performance:** Archiving can significantly improve Dataverse performance by reducing table sizes and index overhead.

### 6. Identify and Clean Up Large Tables
Regularly review your Dataverse capacity reports in PPAC to identify which tables are consuming the most Database capacity.
- **Problem:** Unnecessary custom tables, temporary data, or inefficient data models can lead to bloat and wasted capacity.
- **Best Practice:**
    -   **Review custom tables:** Are they still needed? Can data be purged or archived? Are there duplicate tables?
    -   **Identify and clean up temporary or staging tables:** Ensure these are regularly cleared after data processing.
    -   **Optimize data imports:** Ensure data is clean, de-duplicated, and only necessary fields are imported before populating Dataverse tables.
- **Common Mistake:** Importing large datasets without proper planning for data quality and lifecycle management, leading to accumulation of redundant or obsolete data.

## Things to Remember

-   Dataverse capacity is calculated and pooled at the **Tenant** level, not per environment.
-   Storage is logically split into three cost-optimized buckets: **Database** (relational data), **File** (attachments, binaries), and **Log** (audit, traces).
-   A capacity deficit prevents **environment creation/restoration** and can eventually restrict user access, severely impacting business continuity.
-   Prioritize **optimization** strategies over purchasing add-ons to manage costs effectively.
-   Key optimization strategies include managing **Audit Logs**, offloading **File Attachments** (e.g., to SharePoint), controlling **Plugin Trace Logs**, and purging **Asynchronous System Jobs**.
-   Regularly monitor capacity usage in the **Power Platform Admin Center (PPAC)** to proactively address growth.

## Related Topics

-   **Dataverse Data Management:** Learn more about importing, exporting, and managing data lifecycle within Dataverse.
-   **Power Platform Admin Center Overview:** Understand how to administer your Power Platform environments and monitor resources.
-   **Integrating Dataverse with SharePoint:** Detailed guide on configuring and leveraging SharePoint for document management and file offloading.
-   **Dataverse Long-Term Retention:** Explore advanced archiving capabilities for historical data within Dataverse.
-   **Monitoring and Analytics in Power Platform:** Discover tools for tracking performance, usage, and health of your Power Platform solutions.
  `.trim(),
};