import { DocContent } from "@/types/docs";

export const images: DocContent = {
  title: "Plugin Images",
  description:
    "Plugin images (Pre-Image and Post-Image) allow your C# code to access the state of a record exactly as it was before and after the database operation.",
  content: `
## Introduction

When you register a plugin on the \`Update\` message, Dataverse optimizes performance by only passing the fields that actually changed into your plugin (this package is called the **Target**).

But what if your business logic requires data that *didn't* change? 
- *Example:* A user updates the \`Status\` of an Opportunity to "Won". Your plugin needs to send a congratulatory email. To do this, it needs the \`Owner ID\` and the \`Estimated Value\`. However, because the user only changed the Status, the \`Owner ID\` and \`Estimated Value\` are **not** in the Target.

To get this missing data, you use **Plugin Images**.

## What is it?

An **Image** is a snapshot of the record's data taken by Dataverse at a specific point in the Execution Pipeline.

Instead of writing C# code inside your plugin to manually query the database for the missing \`Owner ID\`, you configure an Image when you register the plugin. Dataverse will automatically take a snapshot of the record and pass it into your plugin's Execution Context.

This is much faster than executing a manual \`Retrieve\` query in your code.

## Types of Images

There are two types of images, depending on when the snapshot is taken:

### 1. Pre-Image (Pre-Entity Image)
A snapshot of the record exactly as it existed in the SQL database *before* the current transaction started.
- **Available in:** Pre-Validation (10), Pre-Operation (20), Post-Operation (40).
- **Use Case:** Comparing old values to new values. *"If the old revenue (Pre-Image) was $500, and the new revenue (Target) is $1000, calculate the difference."*

### 2. Post-Image (Post-Entity Image)
A snapshot of the record exactly as it exists in the SQL database *after* the main SQL transaction (Stage 30) has completed.
- **Available in:** Post-Operation (40) only.
- **Use Case:** Reading fields that are automatically generated by the database during the save. *"The user created an Account. I need to read the auto-generated Account Number (Post-Image) to send to the ERP system."*

## The Target vs Images

It is crucial to understand the difference between the three data packages available in a plugin:

- **Pre-Image:** What the database looked like yesterday.
- **Target:** The specific fields the user is typing into the form *right now*.
- **Post-Image:** What the database looks like *after* the Target is merged with the Pre-Image and saved.

## Configuring an Image

Images are not available by default. They consume memory, so you must explicitly request them using the **Plugin Registration Tool**.

1. Register your Plugin Step (e.g., Update on Account).
2. Right-click the Step and select **Register New Image**.
3. **Image Type:** Choose Pre-Image, Post-Image, or Both.
4. **Entity Alias:** Give the image a name (e.g., \`PreImageAlias\`). You will use this exact string in your C# code to extract the image from the Context.
5. **Parameters:** Select exactly which columns you want included in the snapshot. *Do not select "All Columns" as this degrades performance.*

## Accessing Images in C#

Inside your plugin's \`Execute\` method, you extract the image from the context using the Alias you defined.

\`\`\`csharp
// 1. Get the context
IPluginExecutionContext context = (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));

// 2. Check if the Pre-Image exists (preventing null reference crashes)
if (context.PreEntityImages.Contains("PreImageAlias") && context.PreEntityImages["PreImageAlias"] is Entity)
{
    // 3. Extract the image
    Entity preImage = (Entity)context.PreEntityImages["PreImageAlias"];

    // 4. Read the old data
    if (preImage.Contains("revenue"))
    {
        Money oldRevenue = preImage.GetAttributeValue<Money>("revenue");
    }
}
\`\`\`

## Best Practices

- **Only request necessary columns:** When configuring the image in the Registration Tool, only check the boxes for the 2 or 3 columns your code actually needs.
- **Check for existence:** Always use \`.Contains("FieldName")\` before attempting to read a value from an Image or Target, otherwise your plugin will throw a \`KeyNotFoundException\`.
- **Use Images instead of queries:** If you need data about the record the plugin is running against, always use an Image. Never write a \`service.Retrieve()\` call in your plugin to fetch the current record. 

## Common Mistakes

> [!WARNING]
> **Trying to use a Pre-Image on a Create message** — A Pre-Image is a snapshot of the database *before* the transaction. If the message is \`Create\`, the record does not exist in the database yet. Therefore, you cannot configure a Pre-Image for a Create message. 

## Things to Remember

- **Pre-Images** show data *before* the change.
- **Post-Images** show data *after* the change.
- Images must be manually configured in the **Plugin Registration Tool**.
- Use the **Entity Alias** to retrieve the image in C#.

## Related Topics

- [Plugin Messages](/docs/plugins/messages) — why the Update message requires Images
- [Execution Context](/docs/plugins/execution-context) — the object that holds the Target and Images

## What's Next

We know about the Target and Images, but how do we actually access them in our C# code? Next, we will cover the **IPluginExecutionContext**.
  `.trim(),
};
