import { DocContent } from "@/types/docs";

export const ciCdPipelines: DocContent = {
  title: "CI/CD Pipelines & Automation",
  description:
    "Automating Export, Pack, and Deploy workflows using Azure DevOps or GitHub Actions.",
  content: `
## Why Automate?

If you rely on developers manually clicking "Export" in Dev and "Import" in UAT, you will eventually fail. Manual deployments lead to:
1. Forgotten dependency checks.
2. Inconsistent version numbers.
3. Unmanaged active layers left behind.
4. Overwritten connection references.

To solve this, professional Dynamics 365 projects use **Power Platform Build Tools** integrated into Azure DevOps or GitHub Actions.

---

## The Build Pipeline (CI)

The Continuous Integration (CI) pipeline runs when a developer merges their XML branch into \`develop\` or \`main\`. It does not deploy to a live environment; its sole job is to validate the XML and create a deployable artifact (the \`.zip\` file).

### Standard Build Steps:
1. **Tool Installer:** Installs the \`pac\` CLI on the build agent.
2. **Pack Solution:** Converts the XML source code from Git into a Managed and Unmanaged \`.zip\` file.
3. **Power Apps Checker:** Submits the packed solution to Microsoft's cloud static analysis tool to ensure no deprecated API calls or performance bottlenecks exist.
4. **Publish Artifact:** Saves the generated Managed \`.zip\` file as a build artifact for the Release pipeline.

---

## The Release Pipeline (CD)

The Continuous Deployment (CD) pipeline takes the artifact generated by the Build pipeline and deploys it to a target environment (e.g., UAT or PROD).

### Standard Release Steps:
1. **Service Principal Auth:** Authenticates to the target environment using an Azure App Registration (Service Principal). Never use a licensed user account for automated deployments, as MFA and password expiration will break your pipelines.
2. **Apply Deployment Settings:** Injects the \`deploymentSettings.json\` file. This maps the Connection References to the correct Service Accounts in UAT and updates Environment Variables (e.g., pointing the SharePoint URL to the UAT site).
3. **Import Solution (As Managed):** Pushes the Managed \`.zip\` into the target Dataverse environment.
4. **Publish Customizations:** Ensures all UI and caching layers are refreshed in the target environment.

> [!CAUTION]
> **Never Import Unmanaged Solutions to UAT/PROD**
> The biggest mistake a team can make is deploying Unmanaged solutions downstream. Unmanaged solutions merge directly into the Default Solution of the target environment. If you deploy an unmanaged table to PROD and later decide you want to delete it, you cannot. You must deploy **Managed Solutions** so they can be cleanly uninstalled.

---

## Versioning Strategies

How do you track which version of your code is in UAT?

Your CI pipeline should automatically update the Solution Version XML tag before packing. The standard format is \`Major.Minor.Build.Revision\`.

*   **Major**: Massive architectural shifts.
*   **Minor**: Sprints or monthly releases.
*   **Build**: Automatically generated by the Azure DevOps Build ID (e.g., \`20231015\`).
*   **Revision**: The incremental run number for that day.

By dynamically updating the version in the pipeline, you guarantee that the version number in the Dataverse UI exactly matches the pipeline run that generated it, providing perfect traceability.
`,
};
