import { DocContent } from "@/types/docs";

export const alternateKeys: DocContent = {
  title: "Alternate Keys in Dataverse",
  description:
    "Alternate Keys provide a way to uniquely identify Dataverse records using your own business data instead of the system-generated GUID. They are essential for clean data integration.",
  content: `
## Introduction

When you create a record in Dataverse, the system automatically assigns it a unique 32-character ID (a GUID). For example, a Contact might have the ID \\\`a1b2c3d4-e5f6-7890-abcd-1234567890ab\\\`.

Dataverse uses this GUID internally to link records together. However, external systems (like an ERP, SAP, or a billing system) do not know what this GUID is. They identify customers using their own IDs, like an "Account Number" (e.g., \\\`CUST-1004\\\`). 

Bridging the gap between the internal GUID and external identifiers is the job of **Alternate Keys**.

## What is it?

An **Alternate Key** is a configuration applied to a Dataverse table that defines one or more columns as a secondary unique identifier for the records in that table.

Once defined, Dataverse will guarantee that no two records can have the same value in those columns, and you can use those columns to update records via the Web API *instead* of using the GUID.

## Why do we need it? (Decision Making)

Alternate keys solve two major enterprise problems:

### 1. Upsert Integrations (Update or Insert)
If your external ERP system sends a nightly batch of 10,000 customers to Dynamics 365, the integration needs to know: *Does this customer already exist in D365?* 

Without an Alternate Key, the integration has to query D365 for every single record to check if it exists, which is incredibly slow and burns API limits. With an Alternate Key, the integration simply says, *"Upsert this data using ERP Customer Number '12345'."* Dataverse automatically finds the record and updates it, or creates a new one if it doesn't exist.

\`\`\`text
External ERP
      │ (Sends: Upsert Account where AccountNumber = '12345')
      ▼
Dataverse Web API
      │ (Checks Alternate Key SQL Index)
      ├───────────┐
      ▼           ▼
 (Match Found)   (No Match)
 UPDATE Row      INSERT Row
\`\`\`

### 2. Data Integrity (Uniqueness)
If your business rule dictates that no two products can have the same SKU, configuring an Alternate Key on the \\\`SKU\\\` column enforces this rule at the absolute database level, preventing dirty data.

## How does it work?

You create an Alternate Key in the Dataverse table settings. You can select a single column, or a combination of columns (composite key).

**Allowed column types for Alternate Keys:**
- Single Line of Text
- Whole Number
- Decimal Number
- Date and Time
- Lookup

*Example of a Composite Key:* You might define an Alternate Key using both \\\`First Name\\\` + \\\`Last Name\\\` + \\\`Email\\\`. Dataverse will only block creation if all three fields exactly match an existing record.

When you create the key, Dataverse provisions a unique SQL index on the underlying database in the background.

## Real-world Perspective: Background Jobs

> [!WARNING]
> **Check the System Job Status** 
> Creating an Alternate Key triggers an asynchronous background system job to build the SQL index. If you have millions of rows, this can take hours. Furthermore, if there are *already* duplicate records in the database, the job will fail silently. You must clean up existing duplicates before the key can successfully activate.

## Best Practices

- **Use for Integrations:** If you are building an integration with an external system that owns the master data, you should *always* create an Alternate Key in Dataverse to hold that system's native ID.
- **Do not use for UI validation:** While Alternate Keys do prevent users from saving duplicate records on the form (it throws a hard, ugly error), they are a strict database-level constraint, not a gentle user warning. If you just want to gently warn a user that a record might be a duplicate, use **Duplicate Detection Rules** instead.

## Things to Remember

- Every record has a **Primary Key (GUID)** generated by Dataverse.
- **Alternate Keys** allow you to define unique identifiers using your business data (like Account Number).
- They enable lightning-fast **Upsert** operations for external integrations without querying.
- They enforce strict, database-level uniqueness.

## What's Next

Alternate keys throw hard database errors if duplicates occur. But what if you want to allow a duplicate in certain scenarios, and just gently warn the user in the UI? Next, we look at **Duplicate Detection**.
  `.trim(),
};
