import { DocContent } from "@/types/docs";

export const imagesWebResources: DocContent = {
  title: "Image Web Resources",
  description:
    "Learn how to manage and deploy SVG, PNG, and JPG images as Web Resources for icons, buttons, and custom UI in Dynamics 365.",
  content: `
## Introduction

Dynamics 365 relies heavily on visual iconography to guide users. Whether it's the icon for a custom Table in the sitemap, the image on a custom Ribbon button, or a logo on an HTML dashboard, you must store these assets in Dataverse.

You do this using **Image Web Resources**.

## Supported Formats

Dataverse supports several image formats:
- **SVG (Scalable Vector Graphics):** The modern standard. SVGs are lightweight, XML-based vector graphics that scale infinitely without pixelating. **Microsoft strongly recommends using SVGs for all custom icons.**
- **PNG:** Supports transparency. Historically used for 16x16 and 32x32 ribbon icons, but now largely replaced by SVG.
- **JPG/JPEG:** Used for high-resolution photos (e.g., product images or employee portraits shown in custom HTML).
- **GIF:** Supported, but rarely used in modern enterprise UIs.
- **ICO:** Deprecated for most UI elements.

## Common Use Cases

### 1. Table (Entity) Icons
When you create a custom table, it gets a generic puzzle-piece icon. You can upload an SVG Web Resource and assign it to the table to make it visually distinct in the left-hand navigation Sitemap and on lookup fields.

### 2. Ribbon & Command Bar Buttons
When you create a custom command, you must assign an icon so it doesn't appear as a blank square. 
- In the **Modern Command Designer**, you can select from hundreds of native Microsoft icons, or bind the command to an SVG Web Resource.
- In the **Classic Ribbon XML**, you assign the Web Resource to the \`Image32by32\` and \`Image16by16\` properties.

### 3. HTML & PCF Assets
If you build a custom HTML dashboard, you use relative paths to display images hosted in Dataverse.
\`<img src="con_company_logo.png" alt="Contoso Logo" />\`

## The Importance of SVG

Before the Unified Interface (UCI), developers had to create and upload multiple versions of every icon (16x16 for the sitemap, 32x32 for the ribbon, 64x64 for mobile).

With the shift to modern, responsive design, you now only need to upload **one SVG file**. The Dynamics 365 rendering engine will mathematically scale the SVG to fit the sitemap, the mobile app, or the ribbon perfectly, without any blurriness.

## Best Practices

- **Naming Convention:** Prefix image names clearly (e.g., \`con_icon_credit_card.svg\`).
- **Optimize SVGs:** SVGs generated by design tools like Adobe Illustrator often contain massive amounts of unnecessary metadata. Use tools like SVGOMG to strip the metadata and reduce the file size before uploading to Dataverse.
- **Avoid Base64 inside HTML:** While you *can* embed Base64 encoded images directly into HTML or CSS strings, it severely bloats the code size. It is much better for performance to upload the image as a separate Web Resource and let the browser cache it independently.

## Things to Remember

- Use **SVG** for all icons (Table icons, Ribbon buttons, Sitemap).
- SVGs scale perfectly across **desktop and mobile**.
- Uploading an image to Dataverse makes it a **Web Resource** with a unique URL.
  `.trim(),
};
